{
    name: 'mSCAN',

    description: 'Multilingual SCAN aims to measure compositional and cross-lingual generalization in multilingual LLMs.',

    keywords: [
        'cross-lingual',
        'compositional',
        'LLMs',
    ],

    authors: [
        'Amélie Reymond',
        'Shane Steinert-Threlkeld',
    ],

    subtasks_order: [
        'cmn_add_prim_jump',
        'cmn_add_prim_turn_left',
        'cmn_length',
        'cmn_mcd1',
        'cmn_mcd2',
        'cmn_mcd3',
        'cmn_simple',
        'eng_add_prim_jump',
        'eng_add_prim_turn_left',
        'eng_length',
        'eng_mcd1',
        'eng_mcd2',
        'eng_mcd3',
        'eng_simple',
        'fra_add_prim_jump',
        'fra_add_prim_turn_left',
        'fra_length',
        'fra_mcd1',
        'fra_mcd2',
        'fra_mcd3',
        'fra_simple',
        'hin_add_prim_jump',
        'hin_add_prim_turn_left',
        'hin_length',
        'hin_mcd1',
        'hin_mcd2',
        'hin_mcd3',
        'hin_simple',
        'rus_add_prim_jump',
        'rus_add_prim_turn_left',
        'rus_length',
        'rus_mcd1',
        'rus_mcd2',
        'rus_mcd3',
        'rus_simple',
        
    ],
}